add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '

[[battery.display]]
threshold = 100
style = 'bold green'

[[battery.display]]
threshold = 10
style = 'bold red'
discharging_symbol = '💀 '

[[battery.display]]
threshold = 50
style = 'bold yellow'
discharging_symbol = '💦'
